<?php 
$collection = $this->getImages();
$imageData = $collection->getData();

$catCollection = $this->getCategoryData();
$catData = $catCollection->getData();

?>
<div class="image-gallery-outer">
<div class="category-desc">
<?php foreach($catData as $key => $value)
{
	?>
	<div class="title">
		<h3><?php echo $value['category_title']?></h3>
		</div>
	
	<?php if($value['category_img']): ?>
		<div class="cat-img">
			<img src="<?php echo Mage::getBaseUrl('media').$value['category_img'] ?>" title="<?php echo $value['category_title'] ?>" alt="<?php echo $value['category_title'] ?>"/>
		</div>
        <?php //echo Mage::getBaseUrl('media'); ?>
	<?php endif; ?>
	
	<?php if($value['category_description']): ?>
		<div class="cat-desc"><?php echo $value['category_description'] ?></div>
		<?php endif; ?>
	<?php
}
?>
</div>

<div class="image-detail">
<ul id="masonry-loop"  class="image-gallery">
<?php foreach($imageData as $data){ ?>
	<?php //print_r($data); ?>
	<li class="gallery-item masonry-entry">
		<div class="img-box">
		<div class="img-box-inner">
			<a class="imagegallery" href="<?php echo Mage::getBaseUrl('media').$data['gallery_img']; ?>" title="<?php echo $data['image_title'] ?>"><img src="<?php echo Mage::getBaseUrl('media').$data['gallery_img']; ?>" alt="<?php echo $data['image_title'] ?>"/></a>
			<div class="gallery-desc-box">
            <div class="gallery-content">
				<h3 class="gallery-title">
			<a class="imagetitle" href="<?php echo Mage::getBaseUrl('media').$data['gallery_img']; ?>" title="<?php echo $data['image_title'] ?>"><?php echo $data['image_title'] ?></a>
			</h3>
				
				<?php if($data['image_description']): ?>
				<div class="gallery-desc">
					<?php echo $data['image_description'] ?>
				</div>
				<?php endif; ?>			
				<a class="image-link gallery-block "   data-effect="mfp-move-horizontal" href="<?php echo Mage::getBaseUrl('media').$data['gallery_img']; ?>" title="<?php echo $data['image_title'] ?>"><?php echo $data['image_title'] ?>
			<i class="fa"></i>
			</a>
            </div>
			
			</div>
			
			
			</div>
		</div>
	</li>
<?php } ?>
</ul>
</div>
<script type="text/javascript">
	jQuery(document).ready(function(){

	var $container = jQuery('#masonry-loop');
	var number;
	// initialize Isotope
	if($container.width() < 5000 && $container.width()>900){
	number=3;
	}
	if($container.width() > 460 && $container.width() < 900){
	number=2;
	}
	if($container.width() < 460){
	number=1;
	}

	
    var container1 = document.querySelector('#masonry-loop');
    //create empty var msnry
    var msnry;
    // initialize Masonry after all images have loaded
    imagesLoaded( container1, function() {
        msnry = new Masonry( container1, {
            itemSelector:'.masonry-entry',
            "gutter": 0,
			"width":$container.width()/number
        });
    });
 });
</script>
</div>

